server:
  port: 8001
spring:
  application:
    name: researcher-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
feign:
  sentinel:
    enabled: true


